server:
  port: 8080

app:
  firebase-configuration-file: firebase-service-account

spring:
  application:
    name: CITY-UP
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://${AZURE_DB_HOST}:${AZURE_DB_PORT}/${AZURE_DB_NAME}?useSSL=true&serverTimezone=UTC
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC


jwt:
  secret:
    key: 8ebc070bb4a53120cd451cf58f4f48067decc4077a4b8d1f2a6632305cc4c299
  time:
    expiration: 86400000 # 1 day in milliseconds

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
