server:
  port: 8080

spring:
  application:
    name: CITY-UP

  datasource:
    url: jdbc:mysql://localhost:3306/city-up?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 280101
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC